FROM piotrekzie100/pytorch:1.7.0-py38-cuda11.0
RUN apt-get update -yqq && apt-get install -yqq cmake
ENV HOROVOD_GPU_OPERATIONS=NCCL
ENV HOROVOD_WITH_PYTORCH=1
ENV HOROVOD_WITHOUT_TENSORFLOW=1
ENV HOROVOD_WITHOUT_MXNET=1
RUN pip install horovod[pytorch]

